apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - image: {{ .Values.image.repository}}:{{ .Values.image.tag }}
          imagePullPolicy: Always
          name: frontend
          ports:
            - name: frontend
              containerPort: 4200
